#!/bin/sh

MAILDIR="$HOME/Maildir"
MAILFOLDER="templates"
SIGNATURE="$HOME/.signature"
IDENTITY="$HOME/.identity"

link="$1"
title="$2"
signature=`cat "$SIGNATURE"`
identity=`cat "$IDENTITY"`

cat > "$MAILDIR/$MAILFOLDER/new/template.`date +%s`" <<EOM
From: $identity
To:
Bcc: $identity
Subject: $title

$link

-- 
$signature

EOM

mutt_window=`tmux list-windows | grep mutt | head -1 | cut -f1 -d:`
tmux send-keys -t "$mutt_window" "c=$MAILFOLDER" Enter ":exec resend-message" Enter

exit 0

