#!/bin/sh

MAILDIR="$HOME/Maildir/templates"
SIGNATURE="$HOME/.signature"
IDENTITY="$HOME/.identity"

link="$1"
title="$2"
signature=`cat "$SIGNATURE"`
identity=`cat "$IDENTITY"`

cat > "$MAILDIR/new/template.`date +%s`" <<EOM
From: $identity
To:
Bcc: $identity
Subject: $title

$link

--
$signature

EOM

mutt_window=`tmux list-windows | grep mutt | head -1 | cut -f1 -d:`
tmux send-keys -t "$mutt_window" "c=templates" Enter ":exec resend-message" Enter

exit 0

