#!/usr/bin/env python

import sys
import os
from urllib import quote

link = sys.argv[1]
title = sys.argv[2]

# Get the preferred mailer program according to GNOME.
# Throw away extra args (probably just "%s") to avoid shell quoting.

gconf_mailto = "/desktop/gnome/url-handlers/mailto/command"
mailer = os.popen("gconftool-2 --get '%s'" % gconf_mailto).read()
mailer = mailer.split()[0]

# Construct a mailto: uri and launch the mailer.

mailto = "mailto:user@localhost?subject=%s&body=%s" % (quote(title),quote(link))
argv = [mailer,mailto]
os.execvp(argv[0],argv)

